---
- name: include install tasks
  import_tasks: "{{ sanoid_install_source }}.yaml"

- name: create config directory
  file:
    dest: "{{ sanoid_conf_dir }}"
    state: directory
    owner: root
    group: root

- name: generate sanoid config
  ansible.builtin.template:
    src: ../templates/sanoid.conf.j2
    dest: "{{ sanoid_conf }}"
    owner: root
    group: root
    mode: '0700'

- name: enable sanoid prune service
  ansible.builtin.systemd:
    name: sanoid-prune.service
    enabled: yes

- name: enable sanoid timer
  ansible.builtin.systemd:
    name: sanoid.timer
    state: started
    enabled: yes

- name: generate syncoid systemd service
  ansible.builtin.template:
    src: ../templates/syncoid.service.j2
    dest: "/usr/lib/systemd/system/{{ syncoid_service_name }}.service"
    owner: root
    group: root
    mode: '0700'

- name: generate syncoid systemd timer
  ansible.builtin.template:
    src: ../templates/syncoid.timer.j2
    dest: "/usr/lib/systemd/system/{{ syncoid_service_name }}.timer"
    owner: root
    group: root
    mode: '0700'

- name: enable syncoid timer
  ansible.builtin.systemd:
    name: "{{ syncoid_service_name }}.timer"
    state: started
    enabled: yes
    daemon_reload: yes
