---
- name: check systemd {{ systemd_service_type | default('service') }} {{ systemd_service_name }} exists
  stat:
    path: "/usr/lib/systemd/system/{{ systemd_service_name }}.{{ systemd_service_type | default('service') }}"
  register: service_exists
- block:
    - block:
        - name: check if systemd {{ systemd_service_type | default('service') }} {{ systemd_service_name }} has timer
          stat:
            path: "/usr/lib/systemd/system/{{ systemd_service_name }}.timer"
          register: timer_exists
        - name: disable systemd service
          ansible.builtin.systemd:
            name: "{{ systemd_service_name }}.{{ 'timer' if timer_exists.stat.exists else systemd_service_type | default('service') }}"
            state: stopped
            enabled: no
        - name: remove systemd {{ systemd_service_name }} timer unit file
          file:
            dest: "/usr/lib/systemd/system/{{ systemd_service_name }}.timer"
            state: absent
          when: timer_exists.stat.exists
          notify: reload systemd
      when: systemd_remove_timer | default(true)
    - name: remove systemd {{ systemd_service_type | default('service') }} {{ systemd_service_name }} unit file
      file:
        dest: "/usr/lib/systemd/system/{{ systemd_service_name }}.{{ systemd_service_type | default('service') }}"
        state: absent
      notify: reload systemd
  when: service_exists.stat.exists
