---
- block:
    - name: create systemd service override directory
      ansible.builtin.file:
        dest: "/etc/systemd/system/{{ systemd_service_name }}.d/"
        state: directory
        owner: root
        group: root
    - name: generate systemd service override
      ansible.builtin.template:
        src: ../templates/service.override.conf.j2
        dest: "/etc/systemd/system/{{ systemd_service_name }}.d/{{ systemd_service_override_name }}.conf"
        owner: root
        group: root
        mode: '0700'
      notify: reload systemd
  when:
    - systemd_service_overrides is not none
    - systemd_service_overrides | length > 0
  
- block:
    - name: check systemd service override exists
      stat:
        path: "/etc/systemd/system/{{ systemd_service_name }}.d/{{ systemd_service_override_name }}.conf"
      register: override_exists
    - name: remove systemd service override
      file:
        dest: "/etc/systemd/system/{{ systemd_service_name }}.d/{{ systemd_service_override_name }}.conf"
        state: absent
      notify: reload systemd
      when: override_exists.stat.exists
  when: (systemd_service_overrides is none) or (systemd_service_overrides | length == 0)
